// packages/sapphire-react/src/views/RowRenderDelegation.tsx
import type { IColumnRenderItem, IRowRenderItem } from '@sapphire-table/core';
import type { FC } from 'react';
import { useContext, useMemo } from 'react';
import { TableContext } from '../context/TableContext';
import type { VirtualTableType } from '../hooks/useVirtualTable';
import { TableRow } from './TableRow';
import type { PropsWithSlots } from '../types/table';

interface IRowRenderDelegationProps extends PropsWithSlots {
	computedRowStyle?: (row: IRowRenderItem) => string;
	columns: IColumnRenderItem[];
	position: 'left' | 'body' | 'right';
	withExpand?: boolean;
}

export const RowRenderDelegation: FC<IRowRenderDelegationProps> = (props) => {
	const table = useContext(TableContext) as VirtualTableType;

	const targetGrid =
		props.position === 'body'
			? table.bodyGrid
			: props.position === 'left'
				? table.leftGrid
				: table.rightGrid;

	const renderComputeIndex = useMemo(() => {
		const indexList: Array<{
			key: number;
			data: IRowRenderItem;
		}> = [];
		// empty
		if (table.tableRowData.length === 0) {
			return indexList;
		}
		for (
			let index = table.bodyGrid.renderInfo.renderRowStart;
			index <= table.bodyGrid.renderInfo.renderRowEnd;
			index++
		) {
			indexList.push({
				data: table.tableRowData[index],
				key: index,
			});
		}
		return indexList;
	}, [
		table.tableRowData,
		table.bodyGrid.renderInfo.renderRowStart,
		table.bodyGrid.renderInfo.renderRowEnd,
	]);

	return (
		<>
			{renderComputeIndex.map((renderRow) => {
				return (
					<TableRow
						key={table.renderUpdateKey + '_' + renderRow.key}
						rowIndex={renderRow.key}
						rowData={renderRow.data}
						columns={props.columns}
						position={props.position}
						withExpand={props.withExpand}
						slots={props.slots}
						style={{
							width: targetGrid.gridContentWidth + 'px',
						}}
					/>
				);
			})}
		</>
	);
};

// packages/sapphire-vue/src/views/RowRenderDelegation.vue
<template>
	<TableRow
		v-for="renderRow in renderComputeIndex"
		:key="table.renderUpdateKey.value + '_' + renderRow.key"
		:columns="props.columns"
		:row-data="renderRow.data"
		:row-index="renderRow.key"
		:style="{ width: targetGrid.gridContentWidth + 'px' }"
		:position="props.position"
		:with-expand="props.withExpand"
	>
		<template v-for="(_, name) in slots" :key="name" v-slot:[name]="bindValue">
			<slot :name="name" v-bind="bindValue"></slot>
		</template>
	</TableRow>
</template>

<script lang="ts" setup>
import TableRow from './TableRow.vue';
import type { Ref } from 'vue';
import { computed, inject, useSlots } from 'vue';
import type { IColumnRenderItem, IGridDescribe, IRowRenderItem } from '@sapphire-table/core';
import { TABLE_PROVIDER_KEY } from '../constant/table';
import type { VirtualTableType } from '../hooks/useVirtualTable';

interface IRowRenderDelegationProps {
	computedRowStyle?: (row: IRowRenderItem) => string;
	columns: IColumnRenderItem[];
	position: 'left' | 'body' | 'right';
	withExpand?: boolean;
}

const props = defineProps<IRowRenderDelegationProps>();

const slots = useSlots();

const table = inject<VirtualTableType>(TABLE_PROVIDER_KEY) as VirtualTableType;

const targetGrid: Ref<IGridDescribe> =
	props.position === 'body'
		? table.bodyGrid
		: props.position === 'left'
			? table.leftGrid
			: table.rightGrid;

const renderComputeIndex = computed(() => {
	const indexList: Array<{
		key: number;
		data: IRowRenderItem;
	}> = [];
	// empty
	if (table.tableRowData.value.length === 0) {
		return indexList;
	}
	for (
		let index = table.bodyGrid.value.renderInfo.renderRowStart;
		index <= table.bodyGrid.value.renderInfo.renderRowEnd;
		index++
	) {
		indexList.push({
			data: table.tableRowData.value[index],
			key: index,
		});
	}
	return indexList;
});
</script>
