// packages/sapphire-react/src/views/TableExpandWrapper.tsx
import type { FC, PropsWithChildren } from 'react';
import { useContext, useEffect, useRef } from 'react';
import type { IRowRenderItem } from '@sapphire-table/core';
import { TableContext } from '../context/TableContext';
import type { VirtualTableType } from '../hooks/useVirtualTable';

interface IExpandProps extends PropsWithChildren {
	rowData: IRowRenderItem;
	rowIndex: number;
}

export const TableExpandWrapper: FC<IExpandProps> = (props) => {
	const table = useContext(TableContext) as VirtualTableType;

	const expandBodyRef = useRef<HTMLDivElement>(null);

	const sizeObserver = useRef(
		new ResizeObserver((entries: ResizeObserverEntry[]) => {
			if (entries.length) {
				const [target] = entries;
				const element = target.target as HTMLDivElement;
				if (element) {
					if (element.clientHeight === 0) {
						return;
					}
				}
			}
		})
	);

	useEffect(() => {
		if (expandBodyRef.current) {
			sizeObserver.current.observe(expandBodyRef.current);
		}
		return () => {
			sizeObserver.current?.disconnect();
		};
	}, []);

	return (
		<div
			className={'sapphire-table__expand-wrapper'}
			style={{
				height: props.rowData.expandHeight + 'px',
				width: table.bodyWidth + 'px',
				marginTop: props.rowData.renderRowHeight + 'px',
				zIndex: 8,
				opacity: props.rowData.expand ? 1 : 0,
			}}
			ref={expandBodyRef}
		>
			<div className="sapphire-table__expand-body">{props.children}</div>
		</div>
	);
};

// packages/sapphire-vue/src/views/TableExpandWrapper.vue
<template>
	<div
		class="sapphire-table__expand-wrapper"
		:style="{
			height: props.rowData.expandHeight + 'px',
			width: table.bodyWidth.value + 'px',
			marginTop: props.rowData.renderRowHeight + 'px',
			zIndex: 8,
			opacity: props.rowData.expand ? 1 : 0,
		}"
		ref="expandBodyRef"
	>
		<div class="sapphire-table__expand-body">
			<slot name="default"></slot>
		</div>
	</div>
</template>

<script lang="ts" setup>
import type { IRowRenderItem } from '@sapphire-table/core';
import { inject, nextTick, onBeforeUnmount, onMounted, ref } from 'vue';
import type { VirtualTableType } from '../hooks/useVirtualTable';
import { TABLE_PROVIDER_KEY } from '../constant/table';

const props = defineProps<{
	rowData: IRowRenderItem;
	rowIndex: number;
}>();

const table = inject<VirtualTableType>(TABLE_PROVIDER_KEY) as VirtualTableType;

const expandBodyRef = ref<HTMLDivElement>();

const sizeObserver = new ResizeObserver((entries: ResizeObserverEntry[]) => {
	if (entries.length) {
		const [target] = entries;
		const element = target.target as HTMLDivElement;
		if (element) {
			if (element.clientHeight === 0) {
				return;
			}
		}
	}
});

onMounted(() => {
	nextTick().then(() => {
		if (expandBodyRef.value) {
			sizeObserver.observe(expandBodyRef.value);
		}
	});
});

onBeforeUnmount(() => {
	sizeObserver.disconnect();
});
</script>
