// packages/sapphire-react/src/views/TableRow.tsx
import type { CSSProperties, FC } from 'react';
import { useContext, useMemo, useRef } from 'react';
import type {
	IColumnRenderItem,
	IExpandInstance,
	ILoadDataRequestParams,
	IRowRenderItem,
	ITableConfig,
} from '@sapphire-table/core';
import { TableContext } from '../context/TableContext';
import type { VirtualTableType } from '../hooks/useVirtualTable';
import { composeClassName } from '../utils/classNameUtils';
import { TableCell } from './TableCell';
import { TableExpandWrapper } from './TableExpandWrapper';
import type { PropsWithSlots } from '../types/table';

interface ITableRowProps<T = any> extends PropsWithSlots {
	rowIndex: number;
	rowData: IRowRenderItem<T>;
	columns: IColumnRenderItem[];
	computedRowStyle?: (row: IRowRenderItem<T>) => string;
	position: 'left' | 'body' | 'right';
	withExpand?: boolean;
	onHover?(index: number): void;
	onUnHover?(index: number): void;
	style?: CSSProperties;
}

export const TableRow: FC<ITableRowProps> = (props) => {
	const table = useContext(TableContext) as VirtualTableType;

	const columnRef = useRef<HTMLDivElement>(null);

	const isHover = useMemo(() => {
		return table.hoverIndex === props.rowIndex;
	}, [table.hoverIndex]);

	const rowClassNames = useMemo(() => {
		const classNames: Record<string, boolean> = {
			'sapphire-table__table-row': true,
		};
		const computeClass = props.computedRowStyle?.(props.rowData);
		if (computeClass) {
			classNames[computeClass] = true;
		}
		return classNames;
	}, []);

	const columnRenderRange = useMemo(
		() => {
			const rangeIndex: Array<number> = [];
			if (props.position === 'body') {
				if (
					table.bodyGrid.renderInfo.renderColumnStart ===
						table.bodyGrid.renderInfo.renderColumnEnd &&
					table.bodyGrid.renderInfo.renderColumnEnd === 0
				) {
					return rangeIndex;
				}
				for (
					let index = table.bodyGrid.renderInfo.renderColumnStart;
					index <= table.bodyGrid.renderInfo.renderColumnEnd;
					index++
				) {
					rangeIndex.push(index);
				}
			} else if (props.position === 'left') {
				for (let index = 0; index < table.leftColumns.length; index++) {
					rangeIndex.push(index);
				}
			} else {
				for (let index = 0; index < table.rightColumns.length; index++) {
					rangeIndex.push(index);
				}
			}
			return rangeIndex;
		},
		props.position === 'body'
			? [table.bodyGrid.renderInfo.renderColumnStart, table.bodyGrid.renderInfo.renderColumnEnd]
			: props.position === 'left'
				? [table.leftColumns]
				: [table.rightColumns]
	);

	const handleColumnHover = () => {
		table.updateHoverIndex(props.rowIndex);
		props.onHover?.(props.rowIndex);
	};

	const handleColumUnHover = () => {
		table.updateHoverIndex(-1);
		props.onUnHover?.(props.rowIndex);
	};

	const reloadExpandData = async (params: ILoadDataRequestParams) => {
		await table.loadExpandData(props.rowData, params);
		table.updateTableView();
		return props.rowData.expandInnerData.data;
	};

	const expandConfig: ITableConfig = {
		dataLoadMethod: reloadExpandData,
	};

	const expandInstance: IExpandInstance = {
		reloadData: () => table.handleReloadRowData(props.rowIndex),
	};

	return (
		<div
			className={composeClassName(rowClassNames)}
			style={{
				height: props.rowData.renderRowHeight + 'px',
				transform: `translateY(${props.rowData.renderOffset + 'px'})`,
				position: 'absolute',
				willChange: 'transform',
				...props.style,
			}}
		>
			<div
				ref={columnRef}
				className={composeClassName({ 'expand-wrapper-row-hover': isHover })}
				onMouseEnter={handleColumnHover}
				onMouseLeave={handleColumUnHover}
			>
				{columnRenderRange.map((colIndex) => {
					return (
						<TableCell
							formats={table.globalFormatter}
							rowInfo={props.rowData}
							columnInfo={props.columns[colIndex]}
							rowIndex={props.rowIndex}
							columnIndex={colIndex}
							slots={props.slots}
							key={colIndex}
						/>
					);
				})}
			</div>
			{props.withExpand && props.slots?.expandSlots ? (
				<TableExpandWrapper rowData={props.rowData} rowIndex={props.rowIndex}>
					{props.rowData.expand
						? props.slots.expandSlots?.({
								rowInfo: props.rowData,
								expandData: props.rowData.expandInnerData,
								rowIndex: props.rowIndex,
								expandHeight: props.rowData.expandHeight,
								instance: expandInstance,
								config: expandConfig,
							})
						: null}
				</TableExpandWrapper>
			) : null}
		</div>
	);
};

// packages/sapphire-vue/src/views/TableRow.vue
<template>
	<div
		:class="rowClassNames"
		:data-sapphireId="props.rowIndex"
		:style="{
			height: props.rowData.renderRowHeight + 'px',
			transform: `translateY(${props.rowData.renderOffset + 'px'})`,
			position: 'absolute',
			willChange: 'transform',
		}"
	>
		<div
			ref="columnRef"
			:class="{ 'expand-wrapper-row-hover': isHover }"
			@mouseenter="handleColumnHover"
			@mouseleave="handleColumUnHover"
		>
			<template v-for="colIndex in columnRenderRange" :key="colIndex">
				<TableCell
					:formats="table.globalFormatter.value"
					:row-info="props.rowData"
					:column-info="props.columns[colIndex]"
					:row-index="props.rowIndex"
					:column-index="colIndex"
				>
					<template v-for="(_, name) in usageSlots" :key="name" v-slot:[name]="bindValue">
						<slot :name="name" v-bind="bindValue"></slot>
					</template>
				</TableCell>
			</template>
		</div>
		<TableExpandWrapper
			v-if="props.withExpand && slots.sapphireExpandInner"
			:row-data="props.rowData"
			:row-index="props.rowIndex"
		>
			<slot
				name="sapphireExpandInner"
				v-if="props.rowData.expand"
				:rowInfo="props.rowData"
				:expandData="props.rowData.expandInnerData"
				:rowIndex="props.rowIndex"
				:expandHeight="props.rowData.expandHeight"
				:instance="expandInstance"
				:config="expandConfig"
			></slot>
		</TableExpandWrapper>
	</div>
</template>

<script lang="ts" setup>
import { computed, inject, ref, useSlots } from 'vue';
import type {
	IColumnRenderItem,
	IExpandInstance,
	ILoadDataRequestParams,
	IRowRenderItem,
	ITableConfig,
} from '@sapphire-table/core';
import TableCell from './TableCell.vue';
import { TABLE_PROVIDER_KEY } from '../constant/table';
import type { VirtualTableType } from '../hooks/useVirtualTable';
import TableExpandWrapper from './TableExpandWrapper.vue';

interface ITableRowProps<T = any> {
	rowIndex: number;
	rowData: IRowRenderItem<T>;
	columns: IColumnRenderItem[];
	computedRowStyle?: (row: IRowRenderItem<T>) => string;
	position: 'left' | 'body' | 'right';
	withExpand: boolean;
}

const props = defineProps<ITableRowProps>();

const emits = defineEmits(['hover', 'unHover']);

const table = inject<VirtualTableType>(TABLE_PROVIDER_KEY) as VirtualTableType;

const columnRef = ref<HTMLDivElement>();

const slots = useSlots();

const usageSlots = Object.keys(slots).reduce((previousValue, currentValue) => {
	if (currentValue !== 'sapphireExpandInner') {
		previousValue[currentValue] = slots[currentValue];
	}
	return previousValue;
}, {} as any);

const isHover = computed(() => table.hoverIndex.value === props.rowIndex);

const rowClassNames = computed(() => {
	const classNames: Record<string, boolean> = {
		'sapphire-table__table-row': true,
	};
	const computeClass = props.computedRowStyle?.(props.rowData);
	if (computeClass) {
		classNames[computeClass] = true;
	}
	return classNames;
});

const columnRenderRange = computed(() => {
	const rangeIndex: Array<number> = [];
	if (props.position === 'body') {
		for (
			let index = table.bodyGrid.value.renderInfo.renderColumnStart;
			index <= table.bodyGrid.value.renderInfo.renderColumnEnd;
			index++
		) {
			rangeIndex.push(index);
		}
	} else if (props.position === 'left') {
		for (let index = 0; index < table.leftColumns.value.length; index++) {
			rangeIndex.push(index);
		}
	} else {
		for (let index = 0; index < table.rightColumns.value.length; index++) {
			rangeIndex.push(index);
		}
	}
	return rangeIndex;
});

const handleColumnHover = () => {
	table.hoverIndex.value = props.rowIndex;
	emits('hover', props.rowIndex);
};

const handleColumUnHover = () => {
	table.hoverIndex.value = -1;
	emits('unHover', props.rowIndex);
};

const reloadExpandData = async (params: ILoadDataRequestParams) => {
	await table.loadExpandData(props.rowData, params);
	return props.rowData.expandInnerData.data;
};

const expandConfig: ITableConfig = {
	dataLoadMethod: reloadExpandData,
};

const expandInstance: IExpandInstance = {
	reloadData: () => table.handleReloadRowData(props.rowIndex),
};
</script>
